# Generated by Django 2.2 on 2021-01-22 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_remove_survey_answer_survey'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Survey_Answer',
            new_name='SurveyAnswer',
        ),
    ]
